import {randomUUID} from 'node:crypto';
import {ProjectError,type ProjectSnapshot,validateSnapshot} from '../projects/store';
import {lineDiff,type LineChange} from '../revisions/diff';
export interface Draft {id:string;workspaceId:string;projectId:string;baseRevision:string;headRevision:string;runtimeId?:string;taskId?:string;conversationId?:string;snapshot:ProjectSnapshot;createdAt:number;}
export interface MergeConflict {path:string;line:number;base:string;ours:string;theirs:string;}
export interface MergeResult {snapshot?:ProjectSnapshot;conflicts:MergeConflict[];diffs:Record<string,LineChange[]>;}
const lines=(value:string)=>value.split('\n');
function mergeFile(base:string,ours:string,theirs:string,path:string):{value?:string;conflicts:MergeConflict[]}{const b=lines(base),o=lines(ours),t=lines(theirs);if(ours===theirs)return {value:ours,conflicts:[]};if(ours===base)return {value:theirs,conflicts:[]};if(theirs===base)return {value:ours,conflicts:[]};if(b.length!==o.length||b.length!==t.length)return {conflicts:[{path,line:1,base,ours,theirs}]};const result:string[]=[];const conflicts:MergeConflict[]=[];for(let i=0;i<b.length;i++){if(o[i]===t[i])result.push(o[i]);else if(o[i]===b[i])result.push(t[i]);else if(t[i]===b[i])result.push(o[i]);else{conflicts.push({path,line:i+1,base:b[i],ours:o[i],theirs:t[i]});result.push(`<<<<<<< ours\n${o[i]}\n=======\n${t[i]}\n>>>>>>> theirs`);}}return conflicts.length?{conflicts,value:result.join('\n')}:{value:result.join('\n'),conflicts:[]};}
export class DraftService {private drafts=new Map<string,Draft>();create(input:Omit<Draft,'id'|'createdAt'>):Draft{const draft={...input,id:randomUUID(),createdAt:Date.now(),snapshot:validateSnapshot(input.snapshot)};this.drafts.set(draft.id,draft);return draft;}get(workspaceId:string,id:string):Draft{const draft=this.drafts.get(id);if(!draft||draft.workspaceId!==workspaceId)throw new ProjectError('Draft not found',404);return draft;}diff(workspaceId:string,id:string,base:ProjectSnapshot):Record<string,LineChange[]>{const draft=this.get(workspaceId,id),paths=new Set([...Object.keys(base.files),...Object.keys(draft.snapshot.files)]),out:Record<string,LineChange[]>={};for(const path of paths){const before=base.files[path]||'',after=draft.snapshot.files[path]||'';if(before!==after)out[path]=lineDiff(before,after);}return out;}merge(workspaceId:string,base:ProjectSnapshot,ours:ProjectSnapshot,theirs:ProjectSnapshot):MergeResult{const paths=new Set([...Object.keys(base.files),...Object.keys(ours.files),...Object.keys(theirs.files)]),files={...ours.files},conflicts:MergeConflict[]=[],diffs:Record<string,LineChange[]>={};for(const path of paths){const result=mergeFile(base.files[path]||'',ours.files[path]||'',theirs.files[path]||'',path);if(result.value!==undefined)files[path]=result.value;if(result.conflicts.length)conflicts.push(...result.conflicts);if((ours.files[path]||'')!==(theirs.files[path]||''))diffs[path]=lineDiff(ours.files[path]||'',theirs.files[path]||'');}return conflicts.length?{conflicts,diffs}:{snapshot:validateSnapshot({files,assets:{...ours.assets,...theirs.assets}}),conflicts,diffs};}}
