import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {ProjectStore} from '../../lib/projects/store';
import {SqliteProjectRepository} from '../../lib/persistence/sqlite';
import {RunQueue} from '../../lib/runs/queue';
import type {RunAuthority} from '../../lib/runs/types';
async function fixture(t:{after(fn:()=>void):void}){const store=new ProjectStore(':memory:');t.after(()=>store.close());const repo=new SqliteProjectRepository(store),ctx=repo.individualContext('alice'),project=await repo.create(ctx,'Budget dispatch','gateway/model');const authority:RunAuthority={workspaceId:ctx.principal.workspaceId,actorId:ctx.principal.actorId,memberVersion:1,mode:'individual',sessionId:null,origin:'http://127.0.0.1:3100',settingsOwner:'alice',allowLoopback:true,modelBinding:'a'.repeat(64),policyVersion:1};const queue=new RunQueue(store),run=queue.enqueue(authority,{projectId:project.id,baseVersion:1,requestKey:randomUUID(),prompt:'budget',model:'gateway/model',mode:'build',imageIDs:[],confirmCost:true}),worker=queue.acquireWorker('budget-worker')!,job=queue.claim(worker)!;return {store,queue,authority,run,worker,job,project};}
test('P11 reserves the model call before external dispatch and denies exhausted budget',async t=>{const previous=process.env.OPEN_LOVABLE_MAX_MODEL_CALLS;process.env.OPEN_LOVABLE_MAX_MODEL_CALLS='0';try{const f=await fixture(t);assert.throws(()=>f.queue.markModelStarted(f.job),/budget exhausted/i);assert.equal(f.queue.get(f.authority,f.run.id).state,'RUNNING');assert.equal(f.queue.events(f.authority,f.run.id).events.some(e=>e.type==='model.requested'),false);}finally{if(previous===undefined)delete process.env.OPEN_LOVABLE_MAX_MODEL_CALLS;else process.env.OPEN_LOVABLE_MAX_MODEL_CALLS=previous;}});
test('P11 records explicit unknown usage instead of inventing tokens',async t=>{const f=await fixture(t);f.queue.markModelStarted(f.job);f.queue.recordModelResult(f.job,'result',{});assert.equal(f.queue.get(f.authority,f.run.id).outcome,'MODEL_USAGE_UNKNOWN');const event=f.queue.events(f.authority,f.run.id).events.find(e=>e.type==='model.responded');assert.equal(event?.payload.usageState,'MODEL_USAGE_UNKNOWN');});
