import test from 'node:test';
import assert from 'node:assert/strict';
import {RuntimeService} from '../../lib/runtime/service';
import {RuntimeContractError,type RuntimeAdapter} from '../../lib/runtime/contracts';
const identity=(workspaceId='w_a',projectId='p_a',actorId='actor_a')=>({workspaceId,projectId,draftId:'d_a',revisionId:'r_a',runId:'run_a',actorId});
function adapter(calls:string[],clock:()=>number):RuntimeAdapter{return {async create(i){calls.push(`create:${i.projectId}`);return {sandbox:{sandboxId:`sb-${i.projectId}`,url:'http://runtime.invalid',provider:'e2b',createdAt:new Date(clock())},capabilities:{terminal:true,hmr:false,browser:false,temporaryPersistence:true,mobile:false,provider:'e2b',version:'test-1'}};},async apply(ref){calls.push(`apply:${ref.identity.projectId}`);},async execute(ref,spec){calls.push(`execute:${ref.identity.projectId}:${spec.argv.join(' ')}`);return {stdout:'ok',stderr:'',exitCode:0,success:true};},async logs(){return 'logs';},async health(){return true;},async export(){return Buffer.from('artifact');},async destroy(ref){calls.push(`destroy:${ref.identity.projectId}`);}};}
test('P12-A: project B cannot reuse project A runtime or lease',async()=>{const now=1000;const calls:string[]=[];const service=new RuntimeService(adapter(calls,()=>now),undefined,()=>now);const a=await service.create(identity());const b=await service.create(identity('w_b','p_b','actor_b'));assert.notEqual(a.id,b.id);assert.notEqual(a.sandboxId,b.sandboxId);await service.execute(a,'actor_a',{argv:['npm','test']});assert.deepEqual(calls,['create:p_a','create:p_b','execute:p_a:npm test']);await assert.rejects(()=>service.execute(a,'actor_b',{argv:['id']}),/scope/i);});
test('P12-B: forged runtime identity and expired lease are denied before adapter call',async()=>{let now=1000;const calls:string[]=[];const service=new RuntimeService(adapter(calls,()=>now),undefined,()=>now);await assert.rejects(()=>service.create({...identity(),projectId:'../escape'}),/Invalid runtime identity/);const ref=await service.create(identity(),10);now+=11;await assert.rejects(()=>service.execute(ref,'actor_a',{argv:['npm','test']}),/lease/i);assert.deepEqual(calls,['create:p_a']);});
test('P12 capabilities are explicit and unavailable terminal is not guessed',async()=>{const now=1000;const calls:string[]=[];const base=adapter(calls,()=>now);const noTerminal={...base,async create(i){const created=await base.create(i);return {...created,capabilities:{...created.capabilities,terminal:false}};}};const service=new RuntimeService(noTerminal,undefined,()=>now);const ref=await service.create(identity());assert.equal(service.capabilities(ref,'actor_a').terminal,false);await assert.rejects(()=>service.execute(ref,'actor_a',{argv:['npm','test']}),/unavailable/i);assert.deepEqual(calls,['create:p_a']);});

test('P12 factory adapts an existing provider without introducing a second sandbox selector',async()=>{
 const {SandboxFactory}=await import('../../lib/sandbox/factory');
 const runtime=SandboxFactory.createRuntimeFactory('e2b',{});
 const adapter=runtime.createAdapter();
 assert.equal(typeof adapter.create,'function');assert.equal(typeof adapter.execute,'function');
});
test('P12 forged sandbox identity is denied before adapter call',async()=>{const now=1000,calls:string[]=[],service=new RuntimeService(adapter(calls,()=>now),undefined,()=>now),ref=await service.create(identity());const forged={...ref,sandboxId:'other-sandbox'};await assert.rejects(()=>service.health(forged,'actor_a'),/authoritative/i);assert.deepEqual(calls,['create:p_a']);});
