import test from 'node:test';
import assert from 'node:assert/strict';
import {runRepairLoop} from '../../lib/agent/repair';
import {PlanService} from '../../lib/plans/service';
test('P18 repairs a reproduced failure then validates success within budget',async()=>{let attempts=0;const result=await runRepairLoop({maxRepairs:2,maxToolCalls:6,deadlineMs:1000},async()=>`error-${attempts}`,async()=>{attempts++;return 'patch applied'},async()=>({passed:attempts>0,summary:attempts?'form passes':'form still fails'}),()=>Date.now());assert.equal(result.passed,true);assert.ok(result.steps.some(step=>step.phase==='act'));});
test('P18 stops repeated no-progress and never removes a test',async()=>{const result=await runRepairLoop({maxRepairs:3,maxToolCalls:6,deadlineMs:1000},async()=>'same failure',async()=> 'same patch',async()=>({passed:false,summary:'still failing'}),()=>Date.now());assert.equal(result.reason,'no_progress');assert.equal(result.passed,false);});
test('P18 zero tool budget performs no observe, act or validate calls',async()=>{let calls=0;const result=await runRepairLoop({maxRepairs:2,maxToolCalls:0,deadlineMs:1000},async()=>{calls++;return 'failure';},async()=>{calls++;return 'patch';},async()=>{calls++;return {passed:true,summary:'unexpected'};});assert.equal(calls,0);assert.equal(result.reason,'tool_limit');assert.equal(result.passed,false);});
test('P19 only the approved plan digest can authorize execution',()=>{const service=new PlanService(()=>1000),first=service.create('project_a','rev-a',['booking rule'],[{id:'step-1',title:'Implement booking',acceptance:['duplicate rejected']}]),approved=service.approve('project_a',first.id);assert.equal(service.requireApproved('project_a',approved.id).approvedDigest,approved.approvedDigest);const edited=service.edit('project_a',approved.id,['changed rule'],[{id:'step-1',title:'Implement changed booking',acceptance:['new rule']}]);assert.throws(()=>service.requireApproved('project_a',edited.id),/approved/i);});
test('P19 plans are isolated by project and versioned',()=>{const service=new PlanService(),a=service.create('project_a','rev-a',['a'],[{id:'a',title:'A',acceptance:['a']}]),b=service.create('project_b','rev-b',['b'],[{id:'b',title:'B',acceptance:['b']}]);assert.notEqual(a.id,b.id);assert.throws(()=>service.requireApproved('project_b',a.id),/not found/i);});
