import test from 'node:test';
import assert from 'node:assert/strict';
import {docsAdapter,figmaAdapter,sentryAdapter,runAdapter} from '../../lib/connectors/adapters';
test('P32 authorized Figma and docs references return traceable context',()=>{const figma=runAdapter(figmaAdapter,{projectId:'p1',accountId:'a1',resourceId:'file-1',scopes:['file:read']},{frameId:'frame-1',name:'Hero'});assert.equal(figma.adapterId,'figma');assert.equal(figma.projectId,'p1');assert.equal(figma.redacted,true);const docs=runAdapter(docsAdapter,{projectId:'p1',accountId:'a1',resourceId:'doc-1',scopes:['document:read']},{title:'Spec'});assert.equal(docs.contentDigest.length,64);});
test('P32 Sentry error context is tied to the release and secrets are redacted',()=>{const result=runAdapter(sentryAdapter,{projectId:'p1',accountId:'a1',resourceId:'issue-1',releaseId:'release-7',scopes:['issue:read']},{message:'TypeError',stack:'redacted'});assert.equal(result.releaseId,'release-7');assert.throws(()=>runAdapter(sentryAdapter,{projectId:'p1',accountId:'a1',resourceId:'issue-1',scopes:['issue:read']},{service_role:'secret'}),/secret/i);});
test('P32 wrong scope, unavailable adapter, or cross-project resource is not silently adopted',()=>{assert.throws(()=>runAdapter(figmaAdapter,{projectId:'p2',accountId:'a1',resourceId:'file-1',scopes:['document:read']},{}),/scope/i);assert.throws(()=>runAdapter({...figmaAdapter,availability:'connected'},{projectId:'p1',accountId:'a1',resourceId:'file-1',scopes:['file:read']},{}),/not operational/i);assert.throws(()=>runAdapter(docsAdapter,{projectId:'',accountId:'a1',resourceId:'doc-1',scopes:['document:read']},{}),/identity/i);});

test('P32 async adapters preserve project provenance and redact Sentry credentials',async()=>{const {readFigmaFrame}=await import('../../lib/connectors/adapters/figma');const {readSentryIssue}=await import('../../lib/connectors/adapters/sentry');const context={workspaceId:'ws',projectId:'p1',credentialRef:'vault:figma',scopes:['figma:read','sentry:read'],state:'operational' as const};const frame=await readFigmaFrame(context,{fileId:'f',frameId:'fr',accountId:'a',projectId:'p1'},async()=>({fileId:'f',frameId:'fr',name:'Hero'}));assert.equal(frame.provenance.location,'file:f/frame:fr');const issue=await readSentryIssue(context,{issueId:'i',projectId:'p1',release:'rel-1'},async()=>({issueId:'i',release:'rel-1',message:'authorization: super-secret failed',level:'error'}));assert.match(issue.data.message,/REDACTED/);assert.equal(issue.provenance.release,'rel-1');});
test('P32 async adapters reject wrong project and non-operational context',async()=>{const {readFigmaFrame}=await import('../../lib/connectors/adapters/figma');await assert.rejects(()=>readFigmaFrame({workspaceId:'ws',projectId:'p1',credentialRef:'r',scopes:['figma:read'],state:'operational'},{fileId:'f',frameId:'fr',accountId:'a',projectId:'p2'},async()=>({fileId:'f',frameId:'fr',name:'x'})),/another project/i);});
