import test from 'node:test';
import assert from 'node:assert/strict';
import {TestPaymentGateway} from '../../lib/app-integrations/payments';
import {TransactionalEmailService} from '../../lib/app-integrations/email';
import {recordAnalytics,seoMetadata} from '../../lib/app-integrations/observability';
const manifest={appId:'app-1',projectId:'project-1',environment:'test' as const,payments:'app' as const,email:true,analytics:true};
test('P45 test-mode app checkout reconciles idempotently and records consented app analytics',()=>{const gateway=new TestPaymentGateway('secret');const checkout=gateway.createCheckout(manifest,{actorProjectId:'project-1',amountCents:1200,currency:'usd',idempotencyKey:'order-12345678',approvedTestMode:true});assert.equal(gateway.createCheckout(manifest,{actorProjectId:'project-1',amountCents:1200,currency:'usd',idempotencyKey:'order-12345678',approvedTestMode:true}).id,checkout.id);const raw=JSON.stringify({checkoutId:checkout.id,status:'paid'});assert.equal(gateway.handleWebhook(raw,gateway.signature(raw),'delivery-1',manifest,{checkoutId:checkout.id,projectId:'project-1',status:'paid'}).status,'paid');const event=recordAnalytics({appId:'app-1',projectId:'project-1',actorProjectId:'project-1',environment:'test',consent:'granted',name:'checkout.completed',properties:{currency:'USD',amount:1200}});assert.equal(event?.appId,'app-1');assert.equal(event?.projectId,'project-1');});
test('P45 rejects forged or repeated webhook, foreign app events, unauthorized email and unconsented analytics',()=>{const gateway=new TestPaymentGateway('secret');const checkout=gateway.createCheckout(manifest,{actorProjectId:'project-1',amountCents:100,currency:'usd',idempotencyKey:'order-87654321',approvedTestMode:true});const raw=JSON.stringify({checkoutId:checkout.id});assert.throws(()=>gateway.handleWebhook(raw,'0'.repeat(64),'delivery-x',manifest,{checkoutId:checkout.id,projectId:'project-1',status:'paid'}),/signature/i);gateway.handleWebhook(raw,gateway.signature(raw),'delivery-2',manifest,{checkoutId:checkout.id,projectId:'project-1',status:'paid'});assert.throws(()=>gateway.handleWebhook(raw,gateway.signature(raw),'delivery-2',manifest,{checkoutId:checkout.id,projectId:'project-1',status:'paid'}),/already/i);assert.throws(()=>gateway.createCheckout(manifest,{actorProjectId:'foreign',amountCents:100,currency:'usd',idempotencyKey:'order-foreign',approvedTestMode:true}),/mismatch/i);const mail=new TransactionalEmailService();assert.throws(()=>mail.queue({appId:'app-1',projectId:'project-1',actorProjectId:'project-1',to:'user@example.com',template:'email-confirmation',marketingOptIn:true}),/transactional/i);assert.equal(recordAnalytics({appId:'app-1',projectId:'project-1',actorProjectId:'project-1',environment:'test',consent:'denied',name:'ignored',properties:{x:1}}),null);});
test('P45 provides app SEO metadata and rejects unsafe origins or paths',()=>{const seo=seoMetadata({appId:'app-1',origin:'https://app.example.test',title:'Example app',description:'Accessible app',paths:['/','/about']});assert.match(seo.sitemap,/https:\/\/app\.example\.test\/about/);assert.match(seo.robots,/Sitemap/);assert.throws(()=>seoMetadata({appId:'app-1',origin:'http://bad.test',title:'x',description:'x',paths:['/']}),/SEO/i);});
