import test from 'node:test';
import assert from 'node:assert/strict';
import {createAcceptanceReport} from '../../lib/release/acceptance';
import {createSecurityReleaseReport} from '../../lib/release/security';
import {createReleaseCandidate} from '../../lib/release/candidate';

test('P46 records core journey parity with revision and artifact traceability',()=>{const report=createAcceptanceReport('core-parity',[{id:'crud',input:'authorized workspace',revision:'abc1234',environment:'local',steps:['login','create record','restore backup'],result:'passed',artifacts:['logs/run.json','backup/manifest.json']},{id:'calendar',input:'concurrent editors',revision:'abc1234',environment:'local',steps:['open calendar','conflict','recover'],result:'blocked',artifacts:[],externalDependency:'external identity provider'}]);assert.equal(report.status,'blocked');assert.match(report.digest,/^[a-f0-9]{64}$/);});
test('P47 blocks release on unresolved critical/high findings and preserves measured recovery data',()=>{const blocked=createSecurityReleaseReport({revision:'abc1234',findings:[{id:'idor',category:'idor',severity:'high',status:'open',evidence:'cross-tenant request rejected'}],p95Ms:120,rpoMinutes:15,rtoMinutes:30});assert.equal(blocked.releaseAllowed,false);const clear=createSecurityReleaseReport({revision:'abc1234',findings:[{id:'idor',category:'idor',severity:'high',status:'fixed',evidence:'negative test'}],p95Ms:120,rpoMinutes:15,rtoMinutes:30});assert.equal(clear.releaseAllowed,true);});
test('P48 creates a release candidate with rollback, SBOM and optional extras disclosed',()=>{const candidate=createReleaseCandidate({version:'2.0.0',revision:'abc1234',artifact:new Uint8Array([1,2,3]),migrations:['migration-5'],sbom:['next@15.5.26'],guidePath:'docs/operator-guide.md',rollbackRevision:'def5678',optionalExtras:['external-email-provider (requires authorization)']});assert.equal(candidate.status,'candidate');assert.equal(candidate.migrations.length,1);assert.equal(candidate.optionalExtras.length,1);assert.match(candidate.artifactDigest,/^[a-f0-9]{64}$/);assert.throws(()=>createReleaseCandidate({version:'2.0.0',revision:'abc1234',artifact:new Uint8Array(),migrations:[],sbom:[],guidePath:'README.md',rollbackRevision:'def5678',optionalExtras:[]}),/incomplete/i);});
