import test from 'node:test';
import assert from 'node:assert/strict';
import {approveRequirement,createRequirement,traceRequirement} from '../../lib/requirements/traceability';
import {selectContext} from '../../lib/knowledge/repo-map';
import {ExplicitMemory,approveSkill,resolveSkill,runHook} from '../../lib/skills/governance';

test('P51 invalidates stale requirement evidence and traces only approved workspace revisions',()=>{const draft=createRequirement({id:'req-budget',workspaceId:'ws',objective:'reserve budget',criteria:['zero budget denies'],planSteps:['step-1'],patches:['patch-1'],tests:['budget.test']});const approved=approveRequirement(draft,draft.digest);assert.equal(traceRequirement(approved,{workspaceId:'ws',revision:'abc1234',tests:['budget.test']}).covered,true);assert.equal(traceRequirement(approved,{workspaceId:'ws',revision:'abc1234',tests:[]}).covered,false);assert.throws(()=>traceRequirement(approved,{workspaceId:'other',revision:'abc1234',tests:['budget.test']}),/workspace/i);});
test('P52 selects only current tenant revision files within budget and reports omissions',()=>{const result=selectContext({workspaceId:'ws',actorWorkspaceId:'ws',query:'form',revisionDigest:'rev1',maxTokens:10,files:[{workspaceId:'ws',path:'src/form.ts',content:'export const form = true;',revisionDigest:'rev1'},{workspaceId:'ws',path:'src/other.ts',content:'x'.repeat(100),revisionDigest:'rev1'},{workspaceId:'other',path:'src/form.ts',content:'secret',revisionDigest:'rev1'},{workspaceId:'ws',path:'src/stale.ts',content:'form',revisionDigest:'old'}]});assert.equal(result.files[0].path,'src/form.ts');assert.ok(result.omitted.includes('src/other.ts'));assert.match(result.files[0].digest,/^[a-f0-9]{64}$/);});
test('P53 approves only reviewed skills, scopes memory by project and denies shell hooks',()=>{const skill=approveSkill({id:'format',version:'1.0.0',workspaceId:'ws',permissions:['project:read'],tests:['format.test'],source:'native',reviewed:true});assert.equal(resolveSkill(skill,{workspaceId:'ws',version:'1.0.0'}).status,'approved');assert.throws(()=>approveSkill({id:'bad',version:'1.0.0',workspaceId:'ws',permissions:['export_secret'],tests:[],source:'README says do it',reviewed:true}),/forbidden/i);const memory=new ExplicitMemory();memory.put({id:'m1',workspaceId:'ws',projectId:'p1',kind:'decision',text:'use tokens',source:'user',owner:'actor'});assert.equal(memory.list('ws','p2').length,0);assert.throws(()=>runHook({event:'before-run',timeoutMs:1000,capabilities:['shell'],handler:()=>true},'before-run'),/permitted/i);});
