name = "open-lovable"
compatibility_date = "2024-08-19"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[build.environment_variables]
NODE_VERSION = "20"

[[build.environment_variables]]
NEXT_TELEMETRY_DISABLED = "1"

[vars]
NODE_ENV = "production"

# Environment variables (set via Cloudflare Dashboard)
# OPENAI_API_KEY = "sk-your-openai-key-here"
# ANTHROPIC_API_KEY = "sk-ant-your-anthropic-key-here" 
# E2B_API_KEY = "e2b-your-e2b-key-here"
# KEYSTORE_PASSWORD = "your-keystore-password"
# KEY_PASSWORD = "your-key-password"

[pages_build_output_dir = "out"]

# For Next.js static export
[[redirects]]
from = "/*"
to = "/index.html"
status = 200