import test from 'node:test';
import assert from 'node:assert/strict';
import {startIdentityFixture} from './helpers/identity-fixture';
const origin='http://127.0.0.1:3906';
const request=(path:string,body?:unknown,cookie='')=>new Request(origin+path,{method:body===undefined?'GET':'POST',headers:{host:'127.0.0.1:3906',origin,'Content-Type':'application/json',cookie},body:body===undefined?undefined:JSON.stringify(body)});
test('P05 teams can create, invite, switch, collaborate and revoke without trusting client roles',async t=>{
 const fixture=await startIdentityFixture();t.after(()=>fixture.close());
 const env={OPEN_LOVABLE_AUTH_MODE:'supabase',OPEN_LOVABLE_SUPABASE_URL:fixture.url,OPEN_LOVABLE_SUPABASE_PUBLISHABLE_KEY:'sb_publishable_contract',OPEN_LOVABLE_AUTH_ALLOW_LOOPBACK:'1',OPEN_LOVABLE_APP_ORIGIN:origin};Object.assign(process.env,env);t.after(()=>{for(const key of Object.keys(env))delete process.env[key];});
 const auth=await import('../app/api/auth/route'),workspaces=await import('../app/api/workspaces/route').catch(()=>({})) as Record<string,any>;
 assert.equal(typeof workspaces.POST,'function');
 const login=async(email:string)=>{const response=await auth.POST(request('/api/auth',{action:'login',email,password:'identity-contract-password'}));assert.equal(response.status,200);return response.headers.get('set-cookie')!.split(';')[0];};
 const alice=await login('alice@example.test'),bob=await login('bob@example.test');
 const account=await (await auth.GET(request('/api/auth',undefined,bob))).json();const bobId=account.user.id;
 const created=await workspaces.POST(request('/api/workspaces',{action:'create',name:'Design team'},alice));assert.equal(created.status,201,await created.clone().text());
 const w=(await created.json()).workspace;
 const invitation=await workspaces.POST(request('/api/workspaces',{action:'invite',workspaceId:w.id,email:'bob@example.test',role:'editor'},alice));assert.equal(invitation.status,201);
 const invite=(await invitation.json()).invitation;
 assert.equal((await workspaces.POST(request('/api/workspaces',{action:'accept-invite',token:invite.token},bob))).status,200);
 assert.equal((await workspaces.POST(request('/api/workspaces',{action:'accept-invite',token:invite.token},bob))).status,404);
 assert.equal((await workspaces.POST(request('/api/workspaces',{action:'select',workspaceId:w.id},bob))).status,200);
 const settings=await import('../app/api/provider-settings/route');
 const setting={provider:'gateway',version:0,enabled:true,baseURL:'https://gateway.example/v1',apiKey:'workspace-fixture-key',models:['fixture/coder']};
 assert.equal((await settings.POST(request('/api/provider-settings',setting,bob))).status,403);
 assert.equal((await settings.POST(request('/api/provider-settings',setting,alice))).status,200);
 const catalog=await import('../app/api/ai-models/route');
 const c=await catalog.GET(request('/api/ai-models',undefined,bob));assert.equal(c.status,200);assert.equal((await c.json()).models.some((m:{id:string})=>m.id==='gateway/fixture/coder'),true);
 const forbidden=await workspaces.POST(request('/api/workspaces',{action:'change-member',workspaceId:w.id,actorId:bobId,role:'owner',version:1},bob));assert.equal(forbidden.status,403);
 const projects=await import('../app/api/projects/route');
 const pResponse=await projects.POST(request('/api/projects',{action:'create',name:'Shared app',model:'gateway/coder'},bob));assert.equal(pResponse.status,201,await pResponse.clone().text());
 const p=(await pResponse.json()).project;
 assert.equal((await projects.GET(request('/api/projects?id='+p.id,undefined,alice))).status,200);
 const images=await import('../app/api/project-images/route');
 const raster=await (await import('./helpers/raster-fixture')).rasterWithTokenShapedEncoding();
 const upload={action:'upload',projectID:p.id,name:'screen.png',role:'target',data:raster.toString('base64')};
 assert.equal((await images.POST(request('/api/project-images',upload,bob))).status,201);
 const roleChange=await workspaces.POST(request('/api/workspaces',{action:'change-member',workspaceId:w.id,actorId:bobId,role:'viewer',version:1},alice));assert.equal(roleChange.status,200);
 assert.equal((await images.POST(request('/api/project-images',upload,bob))).status,403);
 assert.equal((await projects.POST(request('/api/projects',{action:'save',id:p.id,version:1,snapshot:{files:{},assets:{}},label:'Blocked'},bob))).status,403);
 assert.equal((await workspaces.POST(request('/api/workspaces',{action:'revoke-member',workspaceId:w.id,actorId:bobId,version:2},alice))).status,200);
 assert.equal((await projects.GET(request('/api/projects?id='+p.id,undefined,bob))).status,404);
 const foreign=await projects.GET(request('/api/projects?id='+p.id,undefined,bob));
 const missing=await projects.GET(request('/api/projects?id=44444444-4444-4444-8444-444444444444',undefined,bob));
 assert.deepEqual(await foreign.json(),await missing.json(),'Foreign and missing projects must be indistinguishable');
});
