import {randomUUID} from 'node:crypto';
import {ProjectError} from '../projects/store';
export interface ExecutionContext {runId:string;projectId:string;workspaceId:string;draftId?:string;permissions:string[];}
export interface HarnessSessionSpec {protocolVersion:string;task:string;maxDurationMs:number;requestedPermissions:string[];}
export interface HarnessSessionRef {sessionId:string;runId:string;projectId:string;workspaceId:string;draftId?:string;protocolVersion:string;state:'running'|'disconnected'|'cancelled'|'completed';}
export type HarnessEvent={sessionId:string;sequence:number;kind:'started'|'progress'|'patch'|'artifact'|'result'|'cancelled';payload:Record<string,unknown>;};
export interface HarnessAdapter {start(ctx:ExecutionContext,spec:HarnessSessionSpec):Promise<{sessionId:string;protocolVersion:string}>;resume(sessionId:string):Promise<void>;cancel(sessionId:string):Promise<void>;}
export function assertHarnessSpec(ctx:ExecutionContext,spec:HarnessSessionSpec):void{if(!ctx.runId||!ctx.projectId||!ctx.workspaceId||!spec.task.trim()||spec.maxDurationMs<=0||spec.maxDurationMs>3_600_000)throw new ProjectError('Harness context or bounds are invalid.',400);if(spec.requestedPermissions.some(permission=>!ctx.permissions.includes(permission)))throw new ProjectError('Harness permission exceeds run authority.',403);if(!/^\d+\.\d+$/.test(spec.protocolVersion))throw new ProjectError('Unsupported harness protocol.',409);}
export class HarnessSessionMap {private sessions=new Map<string,HarnessSessionRef>();private lastSequence=new Map<string,number>();start(ctx:ExecutionContext,spec:HarnessSessionSpec,external:{sessionId:string;protocolVersion:string}):HarnessSessionRef{assertHarnessSpec(ctx,spec);if(external.protocolVersion!==spec.protocolVersion)throw new ProjectError('Harness protocol negotiation mismatch.',409);const ref={sessionId:external.sessionId||randomUUID(),runId:ctx.runId,projectId:ctx.projectId,workspaceId:ctx.workspaceId,draftId:ctx.draftId,protocolVersion:spec.protocolVersion,state:'running' as const};this.sessions.set(ref.sessionId,ref);this.lastSequence.set(ref.sessionId,0);return ref;}acceptEvent(event:HarnessEvent):void{const ref=this.sessions.get(event.sessionId);if(!ref||ref.state==='cancelled'||ref.state==='completed')throw new ProjectError('Harness event belongs to an inactive session.',409);const expected=(this.lastSequence.get(event.sessionId)||0)+1;if(event.sequence!==expected)throw new ProjectError('Harness event sequence is not monotonic.',409);this.lastSequence.set(event.sessionId,event.sequence);if(event.kind==='result')ref.state='completed';if(event.kind==='cancelled')ref.state='cancelled';}disconnect(sessionId:string):void{const ref=this.sessions.get(sessionId);if(!ref)throw new ProjectError('Unknown harness session.',404);if(ref.state==='running')ref.state='disconnected';}resume(sessionId:string):HarnessSessionRef{const ref=this.sessions.get(sessionId);if(!ref||ref.state!=='disconnected')throw new ProjectError('Harness session cannot be resumed.',409);ref.state='running';return ref;}get(sessionId:string):HarnessSessionRef|undefined{return this.sessions.get(sessionId);}}
