/** Additive PostgreSQL migration 2. Identity tables remain inaccessible to the project runtime role. */
export const POSTGRES_IDENTITY_SQL=`
CREATE TABLE open_lovable.identity_actors (
 id TEXT PRIMARY KEY,issuer TEXT NOT NULL,subject TEXT NOT NULL,email TEXT NOT NULL,name TEXT NOT NULL,
 active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)),version INTEGER NOT NULL DEFAULT 1 CHECK(version>=1),
 created_at TEXT NOT NULL,UNIQUE(issuer,subject)
);
CREATE TABLE open_lovable.auth_sessions (
 id TEXT PRIMARY KEY,token_hash TEXT NOT NULL UNIQUE,actor_id TEXT NOT NULL REFERENCES open_lovable.identity_actors(id),
 issuer TEXT NOT NULL,actor_version INTEGER NOT NULL,encrypted TEXT NOT NULL,token_version INTEGER NOT NULL DEFAULT 1,
 access_expires_at BIGINT NOT NULL,expires_at BIGINT NOT NULL,last_seen_at BIGINT NOT NULL,revoked_at BIGINT,
 selected_workspace_id TEXT REFERENCES open_lovable.workspaces(id),refresh_lease TEXT,refresh_until BIGINT NOT NULL DEFAULT 0,
 purpose TEXT NOT NULL DEFAULT 'normal' CHECK(purpose IN ('normal','recovery')),created_at TEXT NOT NULL
);
CREATE INDEX sessions_actor ON open_lovable.auth_sessions(actor_id,expires_at);
CREATE TABLE open_lovable.workspace_invites (
 id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES open_lovable.workspaces(id),email TEXT NOT NULL,
 role TEXT NOT NULL CHECK(role IN ('admin','editor','viewer','billing')),token_hash TEXT NOT NULL UNIQUE,
 created_by TEXT NOT NULL,expires_at BIGINT NOT NULL,consumed_at BIGINT,cancelled_at BIGINT,created_at TEXT NOT NULL
);
CREATE INDEX invites_workspace ON open_lovable.workspace_invites(workspace_id,expires_at);
CREATE TABLE open_lovable.identity_rate_limits(bucket TEXT PRIMARY KEY,count INTEGER NOT NULL,expires_at BIGINT NOT NULL);
CREATE TABLE open_lovable.identity_audit(sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,actor_id TEXT NOT NULL,workspace_id TEXT,action TEXT NOT NULL,target_id TEXT NOT NULL,created_at TEXT NOT NULL);
${['identity_actors','auth_sessions','workspace_invites','identity_rate_limits','identity_audit'].map(table=>`ALTER TABLE open_lovable.${table} ENABLE ROW LEVEL SECURITY; ALTER TABLE open_lovable.${table} FORCE ROW LEVEL SECURITY; REVOKE ALL ON open_lovable.${table} FROM PUBLIC;`).join('\n')}
REVOKE ALL ON SEQUENCE open_lovable.identity_audit_sequence_seq FROM PUBLIC;
`;
