export const POSTGRES_RUN_INTEGRITY_SQL=`
CREATE FUNCTION open_lovable.keep_run_control_identity() RETURNS TRIGGER LANGUAGE plpgsql SET search_path=pg_catalog,open_lovable AS $$ BEGIN IF ROW(NEW.run_id,NEW.workspace_id,NEW.actor_id,NEW.authority,NEW.frozen_input,NEW.input_digest,NEW.request_digest,NEW.request_id,NEW.trace_id,NEW.deadline_at,NEW.created_at) IS DISTINCT FROM ROW(OLD.run_id,OLD.workspace_id,OLD.actor_id,OLD.authority,OLD.frozen_input,OLD.input_digest,OLD.request_digest,OLD.request_id,OLD.trace_id,OLD.deadline_at,OLD.created_at) OR (OLD.output IS NOT NULL AND NEW.output IS DISTINCT FROM OLD.output) THEN RAISE EXCEPTION 'Run control identity/output is immutable'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER run_controls_identity_immutable BEFORE UPDATE ON open_lovable.run_controls FOR EACH ROW EXECUTE FUNCTION open_lovable.keep_run_control_identity();
CREATE FUNCTION open_lovable.keep_managed_run_identity() RETURNS TRIGGER LANGUAGE plpgsql SET search_path=pg_catalog,open_lovable AS $$ BEGIN IF EXISTS(SELECT 1 FROM open_lovable.run_controls WHERE run_id=OLD.id) AND ROW(NEW.id,NEW.project_id,NEW.request_key,NEW.prompt,NEW.model,NEW.base_version,NEW.inputs,NEW.created_at) IS DISTINCT FROM ROW(OLD.id,OLD.project_id,OLD.request_key,OLD.prompt,OLD.model,OLD.base_version,OLD.inputs,OLD.created_at) THEN RAISE EXCEPTION 'Run input is immutable'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER managed_run_identity_immutable BEFORE UPDATE ON open_lovable.runs FOR EACH ROW EXECUTE FUNCTION open_lovable.keep_managed_run_identity();
CREATE FUNCTION open_lovable.keep_run_journal() RETURNS TRIGGER LANGUAGE plpgsql SET search_path=pg_catalog,open_lovable AS $$ BEGIN RAISE EXCEPTION 'Run journal is immutable'; END; $$;
CREATE TRIGGER run_journal_immutable BEFORE UPDATE OR DELETE ON open_lovable.run_journal FOR EACH ROW EXECUTE FUNCTION open_lovable.keep_run_journal();
REVOKE ALL ON FUNCTION open_lovable.keep_run_control_identity(),open_lovable.keep_managed_run_identity(),open_lovable.keep_run_journal() FROM PUBLIC;
`;
