import {POSTGRES_RUN_INTEGRITY_SQL} from './postgres-run-integrity';
import {POSTGRES_RUN_SQL} from './postgres-run-schema';
import {createHash} from 'node:crypto';
import type {Pool} from 'pg';
import {POSTGRES_IDENTITY_SQL} from './postgres-identity-schema';
import {POSTGRES_ADMIN_SQL} from './postgres-admin-schema';

/** PostgreSQL control-plane schema v1 corresponds to the existing SQLite schema through migration 4. */
export const POSTGRES_SCHEMA_VERSION=5;
export const POSTGRES_SCHEMA_SQL=`
CREATE TABLE open_lovable.workspaces(id TEXT PRIMARY KEY,legacy_owner TEXT UNIQUE,name TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE open_lovable.workspace_members(workspace_id TEXT NOT NULL REFERENCES open_lovable.workspaces(id),actor_id TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('owner','admin','editor','viewer','billing')),active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)),version INTEGER NOT NULL DEFAULT 1 CHECK(version>=1),PRIMARY KEY(workspace_id,actor_id));
CREATE INDEX memberships_actor ON open_lovable.workspace_members(actor_id,active);
CREATE TABLE open_lovable.projects(id TEXT PRIMARY KEY,owner TEXT NOT NULL,name TEXT NOT NULL,model TEXT NOT NULL,version INTEGER NOT NULL CHECK(version>=1),snapshot TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,workspace_id TEXT NOT NULL REFERENCES open_lovable.workspaces(id));
CREATE INDEX projects_workspace ON open_lovable.projects(workspace_id,updated_at);
CREATE TABLE open_lovable.revisions(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES open_lovable.projects(id),version INTEGER NOT NULL,label TEXT NOT NULL,snapshot TEXT NOT NULL,sha256 TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(project_id,version));
CREATE TABLE open_lovable.runs(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES open_lovable.projects(id),request_key TEXT NOT NULL,prompt TEXT NOT NULL,model TEXT NOT NULL,base_version INTEGER NOT NULL,state TEXT NOT NULL CHECK(state IN ('RUNNING','AWAITING_APPROVAL','SUCCEEDED','FAILED','CANCELLED','INTERRUPTED')),candidate TEXT,explanation TEXT NOT NULL DEFAULT '',error TEXT NOT NULL DEFAULT '',lease_until BIGINT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,inputs TEXT NOT NULL DEFAULT '{"mode":"build","images":[]}',UNIQUE(project_id,request_key));
CREATE UNIQUE INDEX one_active_project_run ON open_lovable.runs(project_id) WHERE state IN ('RUNNING','AWAITING_APPROVAL');
CREATE TABLE open_lovable.messages(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES open_lovable.projects(id),run_id TEXT REFERENCES open_lovable.runs(id),role TEXT NOT NULL CHECK(role IN ('user','assistant','system')),content TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE INDEX messages_project ON open_lovable.messages(project_id,created_at);
CREATE TABLE open_lovable.run_events(sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,run_id TEXT NOT NULL REFERENCES open_lovable.runs(id),type TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE INDEX events_by_run ON open_lovable.run_events(run_id,sequence);
CREATE TABLE open_lovable.provider_settings(owner TEXT NOT NULL,provider TEXT NOT NULL,version INTEGER NOT NULL,encrypted TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(owner,provider));
CREATE TABLE open_lovable.project_documents(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES open_lovable.projects(id),name TEXT NOT NULL,content TEXT NOT NULL,sha256 TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(project_id,sha256));
CREATE TABLE open_lovable.execution_claims(run_id TEXT PRIMARY KEY REFERENCES open_lovable.runs(id),created_at TEXT NOT NULL);
CREATE TABLE open_lovable.project_images(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES open_lovable.projects(id),name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('target','current')),mime TEXT NOT NULL,width INTEGER NOT NULL,height INTEGER NOT NULL,bytes INTEGER NOT NULL,sha256 TEXT NOT NULL,data TEXT NOT NULL,archived INTEGER NOT NULL DEFAULT 0 CHECK(archived IN(0,1)),created_at TEXT NOT NULL);
CREATE INDEX images_by_project ON open_lovable.project_images(project_id,archived);
CREATE FUNCTION open_lovable.workspace_readable(w TEXT) RETURNS BOOLEAN LANGUAGE SQL STABLE SECURITY INVOKER SET search_path=pg_catalog,open_lovable AS $$
 SELECT w=current_setting('open_lovable.workspace_id',true) AND EXISTS(SELECT 1 FROM open_lovable.workspace_members m WHERE m.workspace_id=w AND m.actor_id=current_setting('open_lovable.actor_id',true) AND m.active=1 AND m.role IN ('owner','admin','editor','viewer'));
$$;
CREATE FUNCTION open_lovable.workspace_writable(w TEXT) RETURNS BOOLEAN LANGUAGE SQL STABLE SECURITY INVOKER SET search_path=pg_catalog,open_lovable AS $$
 SELECT w=current_setting('open_lovable.workspace_id',true) AND EXISTS(SELECT 1 FROM open_lovable.workspace_members m WHERE m.workspace_id=w AND m.actor_id=current_setting('open_lovable.actor_id',true) AND m.active=1 AND m.role IN ('owner','admin','editor'));
$$;
CREATE FUNCTION open_lovable.keep_project_workspace() RETURNS TRIGGER LANGUAGE plpgsql SET search_path=pg_catalog,open_lovable AS $$
 BEGIN IF NEW.workspace_id IS DISTINCT FROM OLD.workspace_id THEN RAISE EXCEPTION 'Workspace reassignment is not allowed'; END IF; RETURN NEW; END;
$$;
CREATE TRIGGER projects_keep_workspace BEFORE UPDATE OF workspace_id ON open_lovable.projects FOR EACH ROW EXECUTE FUNCTION open_lovable.keep_project_workspace();
ALTER TABLE open_lovable.workspace_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE open_lovable.workspace_members FORCE ROW LEVEL SECURITY;
CREATE POLICY member_self ON open_lovable.workspace_members FOR SELECT USING(workspace_id=current_setting('open_lovable.workspace_id',true) AND actor_id=current_setting('open_lovable.actor_id',true) AND active=1);
ALTER TABLE open_lovable.workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE open_lovable.workspaces FORCE ROW LEVEL SECURITY;
CREATE POLICY workspace_read ON open_lovable.workspaces FOR SELECT USING(open_lovable.workspace_readable(id));
ALTER TABLE open_lovable.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE open_lovable.projects FORCE ROW LEVEL SECURITY;
CREATE POLICY project_read ON open_lovable.projects FOR SELECT USING(open_lovable.workspace_readable(workspace_id));
CREATE POLICY project_insert ON open_lovable.projects FOR INSERT WITH CHECK(open_lovable.workspace_writable(workspace_id));
CREATE POLICY project_update ON open_lovable.projects FOR UPDATE USING(open_lovable.workspace_writable(workspace_id)) WITH CHECK(open_lovable.workspace_writable(workspace_id));
ALTER TABLE open_lovable.revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE open_lovable.revisions FORCE ROW LEVEL SECURITY;
CREATE POLICY revision_read ON open_lovable.revisions FOR SELECT USING(EXISTS(SELECT 1 FROM open_lovable.projects p WHERE p.id=project_id));
CREATE POLICY revision_insert ON open_lovable.revisions FOR INSERT WITH CHECK(EXISTS(SELECT 1 FROM open_lovable.projects p WHERE p.id=project_id AND open_lovable.workspace_writable(p.workspace_id)));
ALTER TABLE open_lovable.provider_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE open_lovable.provider_settings FORCE ROW LEVEL SECURITY;
${['runs','messages','project_documents','project_images'].map(table=>`ALTER TABLE open_lovable.${table} ENABLE ROW LEVEL SECURITY; ALTER TABLE open_lovable.${table} FORCE ROW LEVEL SECURITY; CREATE POLICY scoped_read ON open_lovable.${table} FOR SELECT USING(EXISTS(SELECT 1 FROM open_lovable.projects p WHERE p.id=project_id));`).join('\n')}
${['run_events','execution_claims'].map(table=>`ALTER TABLE open_lovable.${table} ENABLE ROW LEVEL SECURITY; ALTER TABLE open_lovable.${table} FORCE ROW LEVEL SECURITY; CREATE POLICY scoped_read ON open_lovable.${table} FOR SELECT USING(EXISTS(SELECT 1 FROM open_lovable.runs r WHERE r.id=run_id));`).join('\n')}
REVOKE ALL ON ALL TABLES IN SCHEMA open_lovable FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA open_lovable FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA open_lovable FROM PUBLIC;
`;
export const POSTGRES_SCHEMA_DIGEST=createHash('sha256').update(POSTGRES_SCHEMA_SQL).digest('hex');
/** Applied SQL remains immutable; future changes append a migration with a new digest. */
export const POSTGRES_MIGRATIONS=Object.freeze([
 {version:1,sql:POSTGRES_SCHEMA_SQL,digest:POSTGRES_SCHEMA_DIGEST},
 {version:2,sql:POSTGRES_IDENTITY_SQL,digest:createHash('sha256').update(POSTGRES_IDENTITY_SQL).digest('hex')},
 {version:3,sql:POSTGRES_RUN_SQL,digest:createHash('sha256').update(POSTGRES_RUN_SQL).digest('hex')},
 {version:4,sql:POSTGRES_RUN_INTEGRITY_SQL,digest:createHash('sha256').update(POSTGRES_RUN_INTEGRITY_SQL).digest('hex')},
 {version:5,sql:POSTGRES_ADMIN_SQL,digest:createHash('sha256').update(POSTGRES_ADMIN_SQL).digest('hex')},
]);
/** Rejects missing, reordered, future or rewritten migrations; prefix mode is for explicit upgrades only. */
export function assertPostgresHistory(rows:readonly {version:number;digest:string}[],complete=true):void {
 if(rows.length>POSTGRES_MIGRATIONS.length||(complete&&rows.length!==POSTGRES_MIGRATIONS.length)||rows.some((row,index)=>row.version!==POSTGRES_MIGRATIONS[index].version||row.digest!==POSTGRES_MIGRATIONS[index].digest))throw new Error('Unknown or changed PostgreSQL migration history');
}

function roleIdentifier(role:string):string{if(!/^[a-z][a-z0-9_]{0,62}$/.test(role))throw new Error('Invalid runtime role');return '"'+role+'"';}
/** Operator-only grant path. The application role cannot mutate memberships or stored credentials. */
export async function grantPostgresRuntime(admin:Pool,role:string):Promise<void>{
 const name=roleIdentifier(role),check=await admin.query('SELECT rolsuper,rolbypassrls,rolcreaterole,rolcreatedb FROM pg_roles WHERE rolname=$1',[role]);
 if(check.rowCount!==1||Object.values(check.rows[0]).some(Boolean))throw new Error('Runtime role is missing or privileged');
 await admin.query(`GRANT USAGE ON SCHEMA open_lovable TO ${name}; GRANT SELECT ON open_lovable.schema_migrations,open_lovable.workspaces,open_lovable.workspace_members,open_lovable.projects,open_lovable.revisions,open_lovable.runs,open_lovable.messages,open_lovable.run_events,open_lovable.project_documents,open_lovable.execution_claims,open_lovable.project_images TO ${name}; GRANT INSERT,UPDATE ON open_lovable.projects TO ${name}; GRANT INSERT ON open_lovable.revisions TO ${name}; GRANT EXECUTE ON FUNCTION open_lovable.workspace_readable(TEXT),open_lovable.workspace_writable(TEXT) TO ${name};`);
}
/** Explicit migration command only. Refuses unversioned nonempty schemas and never resets a database. */
export async function migratePostgres(admin:Pool,options:{runtimeRole:string}):Promise<void>{
 roleIdentifier(options.runtimeRole);const client=await admin.connect();let released=false;
 try{
  await client.query('BEGIN');await client.query("SET LOCAL lock_timeout='5s'; SET LOCAL statement_timeout='30s'");
  await client.query("SELECT pg_advisory_xact_lock(hashtextextended('open-lovable-schema-v1',0))");
  const registry=await client.query("SELECT to_regclass('open_lovable.schema_migrations') AS name");
  if(!registry.rows[0].name){
   const existing=await client.query("SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='open_lovable' LIMIT 1");
   if(existing.rowCount)throw new Error('Refusing unversioned nonempty PostgreSQL schema');
   await client.query('CREATE SCHEMA IF NOT EXISTS open_lovable; REVOKE ALL ON SCHEMA open_lovable FROM PUBLIC; CREATE TABLE open_lovable.schema_migrations(version INTEGER PRIMARY KEY,digest TEXT NOT NULL,applied_at TEXT NOT NULL)');
  }
  const versions=await client.query('SELECT version,digest FROM open_lovable.schema_migrations ORDER BY version');
  assertPostgresHistory(versions.rows,false);
  for(const migration of POSTGRES_MIGRATIONS.slice(versions.rows.length)){
   await client.query(migration.sql);
   await client.query('INSERT INTO open_lovable.schema_migrations VALUES($1,$2,$3)',[migration.version,migration.digest,new Date().toISOString()]);
  }
  await client.query('COMMIT');
 }catch(error){try{await client.query('ROLLBACK');}catch{client.release(true);released=true;throw error;}throw error;}
 finally{if(!released)client.release();}
 await grantPostgresRuntime(admin,options.runtimeRole);
}
