import {createHash} from 'node:crypto';
import {ProjectError} from '../../projects/store';
export type AdapterAvailability='available'|'configured'|'connected'|'operational';
export interface AdapterManifest {id:'figma'|'docs'|'sentry';version:string;availability:AdapterAvailability;capabilities:string[];requiredScopes:string[];inputSchema:string;outputSchema:string;}
export interface AdapterContext {projectId:string;accountId:string;resourceId:string;scopes:string[];releaseId?:string;}
export interface AdapterResult {adapterId:string;projectId:string;accountId:string;resourceId:string;retrievedAt:string;sourceUrl?:string;releaseId?:string;contentDigest:string;redacted:boolean;}
export function runAdapter(manifest:AdapterManifest,context:AdapterContext,payload:unknown):AdapterResult{if(manifest.availability!=='operational')throw new ProjectError(`Adapter ${manifest.id} is not operational.`,503);if(!manifest.requiredScopes.every(scope=>context.scopes.includes(scope)))throw new ProjectError('Adapter scope is insufficient.',403);if(!context.projectId||!context.accountId||!context.resourceId)throw new ProjectError('Adapter resource identity is required.',400);const safe=JSON.stringify(payload);if(/(?:access[_-]?token|client[_-]?secret|password|service_role)\s*['"]?\s*:/i.test(safe))throw new ProjectError('Adapter payload contains a secret.',400);return {adapterId:manifest.id,projectId:context.projectId,accountId:context.accountId,resourceId:context.resourceId,retrievedAt:new Date().toISOString(),releaseId:context.releaseId,contentDigest:createHash('sha256').update(safe).digest('hex'),redacted:true};}
export const figmaAdapter:AdapterManifest={id:'figma',version:'1.0',availability:'operational',capabilities:['design-frame-reference'],requiredScopes:['file:read'],inputSchema:'FigmaFrame',outputSchema:'LicensedAssetRef'};
export const docsAdapter:AdapterManifest={id:'docs',version:'1.0',availability:'operational',capabilities:['document-reference'],requiredScopes:['document:read'],inputSchema:'DocumentQuery',outputSchema:'DocumentContext'};
export const sentryAdapter:AdapterManifest={id:'sentry',version:'1.0',availability:'operational',capabilities:['error-event-reference'],requiredScopes:['issue:read'],inputSchema:'ErrorQuery',outputSchema:'RedactedErrorContext'};
