"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {accountRequest,actionClass,fieldClass,useAccount} from '@/components/account/client';
export default function ConfirmAccountPage(){
 const {account,reload,error:sessionError}=useAccount();
 const [challenge,setChallenge]=useState<{tokenHash:string;type:'email'|'signup'|'recovery'}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false),[password,setPassword]=useState(''),[repeat,setRepeat]=useState('');
 useEffect(()=>{const params=new URLSearchParams(window.location.hash.slice(1)||window.location.search.slice(1)),hash=params.get('token_hash')||'',type=params.get('type');if(/^[a-fA-F0-9]{32,128}$/.test(hash)&&(type==='email'||type==='signup'||type==='recovery'))setChallenge({tokenHash:hash,type});window.history.replaceState(null,'','/auth/confirm');},[]);
 async function confirm(){if(!challenge)return;setBusy(true);setError('');try{await accountRequest('/api/auth',{action:'confirm',...challenge});setChallenge(null);await reload();}catch(caught){setError(caught instanceof Error?caught.message:'Não foi possível confirmar o acesso.');}finally{setBusy(false);}}
 async function reset(event:React.FormEvent){event.preventDefault();if(password!==repeat){setError('As senhas precisam ser iguais.');return;}setBusy(true);setError('');try{await accountRequest('/api/auth',{action:'reset-password',password});setPassword('');setRepeat('');setDone(true);}catch(caught){setError(caught instanceof Error?caught.message:'Não foi possível atualizar a senha.');}finally{setBusy(false);}}
 return <main className="min-h-screen bg-[#f7f7f3] px-[20px] py-[48px] text-[#292922]"><section className="mx-auto max-w-lg rounded-lg border border-[#ddddd1] bg-white p-[24px] md:p-[36px]"><p className="mb-[24px] text-sm font-medium text-[#8d482b]">Open Lovable · Sua conta</p><h1 className="text-2xl font-semibold tracking-tight">Confirme seu acesso</h1>
  {(error||sessionError)&&<p role="alert" className="my-[20px] rounded border border-red-200 bg-red-50 p-[16px] text-sm text-red-800">{error||sessionError}</p>}
  {done?<div role="status" className="mt-[24px] space-y-[16px] text-sm"><p>Senha atualizada. As sessões desta instalação foram encerradas. Entre novamente com a nova senha.</p><Link href="/login" className="underline">Entrar</Link></div>:challenge?<><p className="my-[24px] text-sm leading-relaxed text-[#737367]">Use este botão apenas se você solicitou a confirmação ou a recuperação. Abrir a página não consome o código do e-mail.</p><button type="button" disabled={busy} onClick={()=>void confirm()} className={actionClass}>{busy?'Confirmando…':'Confirmar acesso'}</button></>:account?.purpose==='recovery'?<form onSubmit={reset} className="mt-[24px] space-y-[20px]"><p className="break-all text-sm">Recuperação de <strong>{account.user?.email}</strong></p><div><label htmlFor="new-password" className="mb-[8px] block text-sm">Nova senha</label><input id="new-password" type="password" required autoComplete="new-password" minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} disabled={busy} className={fieldClass}/></div><div><label htmlFor="repeat-password" className="mb-[8px] block text-sm">Repita a nova senha</label><input id="repeat-password" type="password" required autoComplete="new-password" minLength={12} maxLength={128} value={repeat} onChange={e=>setRepeat(e.target.value)} disabled={busy} className={fieldClass}/></div><button disabled={busy} className={actionClass}>Atualizar senha</button></form>:account?.authenticated?<div className="mt-[24px] space-y-[20px] text-sm"><p className="break-all">Você está na conta <strong>{account.user?.email}</strong>. Confira o endereço antes de continuar.</p><Link href="/projects" className="underline">Abrir meus projetos</Link></div>:<p className="mt-[24px] text-sm leading-relaxed text-[#737367]">Abra o link completo enviado pelo provedor de conta ou solicite uma nova recuperação na tela de entrada.</p>}
 </section></main>;
}
