import {createHash} from 'node:crypto';
import {normalizeProjectPath} from '../../security/input-validation';
import {ProjectError,type ProjectSnapshot} from '../../projects/store';
export type ToolEffect='read'|'write'|'external';
export interface ToolContext {workspaceId:string;projectId:string;revisionDigest:string;snapshot:ProjectSnapshot;}
export interface ToolDefinition {name:string;effectClass:ToolEffect;description:string;inputSchema:Record<string,unknown>;execute(ctx:ToolContext,input:unknown):Promise<unknown>;}
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
function pathInput(input:unknown):string{if(!input||typeof input!=='object'||typeof (input as {path?:unknown}).path!=='string')throw new ProjectError('Tool path is required',400);return normalizeProjectPath((input as {path:string}).path);}
export function createFileTools():ToolDefinition[]{return [{name:'list_files',effectClass:'read',description:'List authorized snapshot paths',inputSchema:{limit:'integer',offset:'integer'},async execute(ctx,input){const value=(input??{}) as {limit?:number;offset?:number};const limit=Math.min(Math.max(value.limit??100,1),500),offset=Math.max(value.offset??0,0);const paths=Object.keys(ctx.snapshot.files).sort();return {paths:paths.slice(offset,offset+limit),total:paths.length,revisionDigest:ctx.revisionDigest};}},{name:'read_file',effectClass:'read',description:'Read one authorized snapshot file',inputSchema:{path:'string'},async execute(ctx,input){const path=pathInput(input);const content=ctx.snapshot.files[path];if(content===undefined)throw new ProjectError('File not found in authorized snapshot',404);return {path,content,sha256:hash(content),source:'project-snapshot',revisionDigest:ctx.revisionDigest};}},{name:'search_files',effectClass:'read',description:'Search authorized snapshot text',inputSchema:{query:'string',limit:'integer'},async execute(ctx,input){const value=input as {query?:unknown;limit?:unknown};if(typeof value?.query!=='string'||!value.query||value.query.length>200)throw new ProjectError('Search query is invalid',400);const limit=Math.min(Math.max(Number(value.limit??50),1),100),query=value.query.toLowerCase();const matches=Object.entries(ctx.snapshot.files).filter(([,content])=>content.toLowerCase().includes(query)).slice(0,limit).map(([path,content])=>({path,sha256:hash(content),snippet:content.slice(Math.max(0,content.toLowerCase().indexOf(query)-100),content.toLowerCase().indexOf(query)+300)}));return {matches,revisionDigest:ctx.revisionDigest};}},{name:'get_diff',effectClass:'read',description:'Return selected current files and hashes for a candidate',inputSchema:{paths:'string[]'},async execute(ctx,input){const paths=(input as {paths?:unknown})?.paths;if(!Array.isArray(paths)||paths.length>100)throw new ProjectError('Diff paths are invalid',400);return {files:paths.map(path=>{const normalized=normalizeProjectPath(path);const content=ctx.snapshot.files[normalized];if(content===undefined)throw new ProjectError('File not found in authorized snapshot',404);return {path:normalized,sha256:hash(content),content};}),revisionDigest:ctx.revisionDigest};}}];}
export class ToolRegistry {private readonly tools:Map<string,ToolDefinition>;constructor(tools=createFileTools()){this.tools=new Map(tools.map(tool=>[tool.name,tool]));}list(){return [...this.tools.values()].map(({name,effectClass,description,inputSchema})=>({name,effectClass,description,inputSchema}));}async execute(name:string,ctx:ToolContext,input:unknown){const tool=this.tools.get(name);if(!tool)throw new ProjectError('Tool is not registered',404);if(ctx.workspaceId.length<1||ctx.projectId.length<1||!/^[a-f0-9]{64}$/.test(ctx.revisionDigest))throw new ProjectError('Tool context is invalid',403);return tool.execute(ctx,input);}}
