import {createHash} from 'node:crypto';
import {RuntimeContractError} from '../runtime/contracts';

export type TemplateId = 'institutional-site'|'authenticated-crud'|'role-calendar';
export interface TemplateVersion {id:TemplateId;version:string;name:string;dependencies:string[];license:string;compatibility:{runtime:string;targets:string[]};tests:string[];capabilities:string[];scenarios:string[];componentSchemas:string[];roles:string[];integrations:string[];executionTarget:'browser'|'server';distribution:'internal'|'workspace';checklist:string[];sourceDigest:string;}
export interface TemplateCatalog {list():TemplateVersion[];get(id:TemplateId,version?:string):TemplateVersion;publish(template:TemplateVersion,authorizedSourceDigest:string):TemplateVersion;rollback(id:TemplateId,toVersion:string):TemplateVersion;reuse(id:TemplateId,version:string,request:{workspaceId:string;destinationProjectId:string;authorizedSourceDigest:string;confirmedDestination:boolean;allowedDependencies:string[]}):TemplateVersion;}
const source=(id:string,version:string)=>createHash('sha256').update(`${id}:${version}:open-lovable-native`).digest('hex');
const base=(id:TemplateId,version:string,name:string,capabilities:string[],roles:string[],scenarios:string[]):TemplateVersion=>({id,version,name,dependencies:['react','typescript'],license:'MIT',compatibility:{runtime:'node22',targets:['web']},tests:[`tests/templates/${id}.test.ts`],capabilities,scenarios,componentSchemas:['layout','navigation','form','feedback'],roles,integrations:[],executionTarget:'browser',distribution:'workspace',checklist:['Confirm workspace branding tokens','Configure authentication and data source','Run generated template tests'],sourceDigest:source(id,version)});
const builtins:TemplateVersion[]=[
 {...base('institutional-site','1.0.0','Site institucional',['responsive-pages','contact-form'],['public'],['Publish honest company pages without invented testimonials or metrics.']),componentSchemas:['layout','navigation','content-section','contact-form']},
 {...base('authenticated-crud','1.0.0','CRUD autenticado',['authentication','tenant-scoped-crud','optimistic-concurrency'],['admin','editor','viewer'],['Create, read, update and delete tenant-owned records with server authorization.']),integrations:['identity','database'],componentSchemas:['layout','navigation','data-table','record-form','error-state']},
 {...base('role-calendar','1.0.0','Agenda com papéis',['authentication','role-based-calendar','conflict-detection'],['admin','editor','viewer'],['Schedule and review events with role-based mutation and conflict feedback.']),integrations:['identity','database'],componentSchemas:['layout','navigation','calendar','event-form','conflict-alert']},
];
const validVersion=(value:string)=>/^\d+\.\d+\.\d+$/.test(value);
export class InMemoryTemplateCatalog implements TemplateCatalog {private readonly history=new Map<TemplateId,TemplateVersion[]>();constructor(initial=builtins){for(const item of initial)this.history.set(item.id,[structuredClone(item)]);}
 list(){return [...this.history.values()].map(items=>items.at(-1)!).map(item=>structuredClone(item));}
 get(id:TemplateId,version?:string){const items=this.history.get(id)||[];const found=version?items.find(item=>item.version===version):items.at(-1);if(!found)throw new RuntimeContractError('Template version is not available.',404);return structuredClone(found);}
 publish(template:TemplateVersion,authorizedSourceDigest:string){if(!validVersion(template.version)||template.sourceDigest!==authorizedSourceDigest)throw new RuntimeContractError('Template provenance is not authorized.',403);const items=this.history.get(template.id)||[];if(items.some(item=>item.version===template.version))throw new RuntimeContractError('Template version already exists.',409);this.history.set(template.id,[...items,structuredClone(template)]);return structuredClone(template);}
 rollback(id:TemplateId,toVersion:string){const target=this.get(id,toVersion);const items=this.history.get(id)!;const next=`${items.length+1}.0.0`;const restored={...target,version:next,sourceDigest:source(id,next)};this.history.set(id,[...items,restored]);return structuredClone(restored);}
 reuse(id:TemplateId,version:string,request:TemplateCatalog['reuse'] extends (id:TemplateId,version:string,request:infer R)=>TemplateVersion?R:never){if(!request.workspaceId||!request.destinationProjectId||!request.confirmedDestination)throw new RuntimeContractError('Destination confirmation is required for template reuse.',403);const template=this.get(id,version);if(template.sourceDigest!==request.authorizedSourceDigest)throw new RuntimeContractError('Template source authorization does not match.',403);const denied=template.dependencies.filter(dep=>!request.allowedDependencies.includes(dep));if(denied.length)throw new RuntimeContractError(`Template dependencies are not permitted: ${denied.join(', ')}`,403);return template;}}
export {builtins as initialTemplates};
