"use client";
import {useEffect,useState} from 'react';
import type {ProjectSnapshot} from '@/lib/projects/store';
export default function ProjectCode({snapshot,busy,onSave}:{snapshot:ProjectSnapshot;busy:boolean;onSave:(path:string,content:string)=>Promise<void>}){
 const paths=Object.keys(snapshot.files).sort();const [selected,setSelected]=useState(paths[0]||''),[draft,setDraft]=useState(''),[newPath,setNewPath]=useState('');
 useEffect(()=>{if(!Object.hasOwn(snapshot.files,selected))setSelected(Object.keys(snapshot.files).sort()[0]||'');else setDraft(snapshot.files[selected]);},[snapshot,selected]);
 const dirty=Boolean(selected)&&draft!==snapshot.files[selected];
 return <div className="grid min-h-[570px] min-w-0 lg:grid-cols-[215px_1fr]">
  <aside className="min-w-0 border-b border-[#e3e3da] bg-[#fafaf8] p-[16px] lg:border-b-0 lg:border-r"><p className="mb-[12px] text-[11px] font-semibold uppercase tracking-widest text-[#737369]">Arquivos salvos</p><nav aria-label="Arquivos do projeto" className="max-h-[350px] space-y-[4px] overflow-auto">{paths.map(path=><button key={path} type="button" disabled={busy} aria-pressed={selected===path} onClick={()=>{if(!dirty||window.confirm('Descartar a edição não salva deste arquivo?'))setSelected(path);}} className={`block w-full break-all rounded px-[8px] py-[8px] text-left font-mono text-[12px] ${selected===path?'bg-[#eae9e1] text-[#282821]':'text-[#65655c] hover:bg-white'}`}>{path}</button>)}</nav>
   <form className="mt-[20px] border-t border-[#dfdfd6] pt-[16px]" onSubmit={async event=>{event.preventDefault();if(!newPath.trim())return;await onSave(newPath.trim(),'');setSelected(newPath.trim());setNewPath('');}}><label htmlFor="new-file" className="text-[12px] text-[#69695f]">Nome do novo arquivo</label><input id="new-file" value={newPath} onChange={e=>setNewPath(e.target.value)} disabled={busy} placeholder="src/Componente.jsx" className="mt-[6px] w-full min-w-0 rounded border border-[#d2d2c8] bg-white p-[8px] font-mono text-[12px]"/><button type="submit" disabled={busy||!newPath.trim()||Object.hasOwn(snapshot.files,newPath.trim())} className="mt-[8px] text-[12px] font-medium underline disabled:opacity-40">Adicionar arquivo</button></form>
   {Object.keys(snapshot.assets).length>0&&<p className="mt-[18px] text-[12px] leading-relaxed text-[#797970]">{Object.keys(snapshot.assets).length} arquivo(s) binário(s) preservado(s) no ZIP.</p>}
  </aside>
  <section className="flex min-w-0 flex-col">{selected?<><div className="flex flex-wrap items-center justify-between gap-[12px] border-b border-[#e3e3da] px-[18px] py-[12px]"><p className="break-all font-mono text-[12px]">{selected}{dirty?' · Alterações não salvas':''}</p><button type="button" disabled={busy||!dirty} onClick={()=>void onSave(selected,draft)} className="rounded bg-[#282822] px-[14px] py-[9px] text-[12px] font-medium text-white disabled:opacity-40">Salvar arquivo</button></div><textarea aria-label="Conteúdo do arquivo" value={draft} onChange={event=>setDraft(event.target.value)} disabled={busy} spellCheck={false} className="min-h-[480px] w-full flex-1 resize-y border-0 bg-[#fdfdfa] p-[18px] font-mono text-[12px] leading-[1.7] text-[#35352d] focus:outline-none focus:ring-2 focus:ring-inset focus:ring-orange-600"/><p className="border-t border-[#e3e3da] px-[18px] py-[10px] text-[11px] text-[#737369]">Salvar cria uma nova revisão. A compilação é verificada na aba Prévia; versões anteriores permanecem no histórico.</p></>:<p className="p-[24px] text-[14px] text-[#737369]">Importe um projeto, gere uma proposta ou adicione seu primeiro arquivo.</p>}</section>
 </div>;
}
