import {createHash} from 'node:crypto';
import {ProjectError} from '../projects/store';
export interface TaskNode {id:string;dependsOn:string[];objective:string;inputDigests:string[];outputType:'research'|'analysis'|'patch';budget:{tokens:number;ms:number};readOnly:boolean;files:string[];}
export interface TaskGraph {nodes:TaskNode[];totalBudget:{tokens:number;ms:number};}
export interface DelegationPlan {graphDigest:string;tasks:TaskNode[];reserved:{tokens:number;ms:number};status:'planned'|'cancelled';}
const validateGraph=(graph:TaskGraph)=>{const ids=new Set(graph.nodes.map(node=>node.id));if(ids.size!==graph.nodes.length||graph.nodes.some(node=>!node.id||!node.objective||node.budget.tokens<1||node.budget.ms<1||node.dependsOn.some(dep=>!ids.has(dep))))throw new ProjectError('Delegation graph is invalid.',422);const visiting=new Set<string>(),visited=new Set<string>();const visit=(id:string)=>{if(visiting.has(id))throw new ProjectError('Delegation graph contains a cycle.',422);if(visited.has(id))return;visiting.add(id);for(const dep of graph.nodes.find(node=>node.id===id)!.dependsOn)visit(dep);visiting.delete(id);visited.add(id);};for(const id of ids)visit(id);const tokens=graph.nodes.reduce((sum,node)=>sum+node.budget.tokens,0),ms=graph.nodes.reduce((sum,node)=>sum+node.budget.ms,0);if(tokens>graph.totalBudget.tokens||ms>graph.totalBudget.ms)throw new ProjectError('Delegation budget exceeded.',409);};
export function scheduleSubtasks(graph:TaskGraph):DelegationPlan{validateGraph(graph);const tasks=graph.nodes.map(node=>({...node,files:[...node.files],inputDigests:[...node.inputDigests]}));return {graphDigest:createHash('sha256').update(JSON.stringify(tasks)).digest('hex'),tasks,reserved:{tokens:tasks.reduce((sum,node)=>sum+node.budget.tokens,0),ms:tasks.reduce((sum,node)=>sum+node.budget.ms,0)},status:'planned'};}
export function approveHandoff(plan:DelegationPlan,input:{taskId:string;leaseValid:boolean;result:string;artifactDigest?:string;uncertainties:string[]}):{taskId:string;result:string;artifactDigest:string|null;uncertainties:string[]}{if(plan.status!=='planned'||!plan.tasks.some(task=>task.id===input.taskId)||!input.leaseValid)throw new ProjectError('Delegation lease is invalid.',409);return {taskId:input.taskId,result:input.result,artifactDigest:input.artifactDigest||null,uncertainties:[...input.uncertainties]};}
export function mergeDraft(baseFiles:Record<string,string>,writes:Array<{taskId:string;files:Record<string,string>;leaseValid:boolean}>){const seen=new Set<string>(),merged={...baseFiles};for(const write of writes){if(!write.leaseValid)throw new ProjectError('Expired delegation cannot write to draft.',409);for(const path of Object.keys(write.files)){if(seen.has(path))throw new ProjectError('Concurrent writers conflict on draft file.',409);seen.add(path);merged[path]=write.files[path];}}return merged;}
